development: &defaults
  app_id: 114695751918461
  client_id: b190caf64772c780498ea1a5e7ae11b2
  client_secret: 0f52ccb7e7346b3e778e52d6341200cd
  perms: user_about_me,user_activities,user_birthday,user_education_history,user_hometown,user_interests,user_likes,user_location,user_photos,user_relationships,user_relationship_details,user_religion_politics,user_status,user_website,user_work_history,email,read_requests,read_stream,publish_stream # ,user_address,user_mobile_phone

test:
  <<: *defaults

production:
  <<: *defaults
